function num(v){const n=Number(v);return Number.isFinite(n)?n:0;}
function money(v){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(num(v));}
function safeText(v,max=8000){return String(v??'').replace(/\u0000/g,'').slice(0,max);}
function safeArray(v){return Array.isArray(v)?v:[];}
function safeDate(v){const d=new Date(v);return Number.isFinite(d.getTime())?d.toISOString().slice(0,10):'';}
function errorText(e){if(!e)return 'MOVA Ask AI failed';if(typeof e==='string')return e;if(typeof e?.message==='string')return e.message;if(typeof e?.error==='string')return e.error;if(typeof e?.error?.message==='string')return e.error.message;try{return JSON.stringify(e);}catch{return 'MOVA Ask AI failed';}}

function portfolioSummary(raw){
  const holdings=safeArray(raw?.holdings).slice(0,40);
  const rows=holdings.map(h=>{const qty=num(h.qty),avg=num(h.avg),current=num(h.current),value=qty*current,cost=qty*avg,pnl=value-cost,pnlPct=cost?100*pnl/cost:0;return {ticker:safeText(h.ticker,20).toUpperCase(),qty,avg,current,value,cost,pnl,pnlPct};}).filter(x=>x.ticker);
  const holdingsValue=rows.reduce((s,x)=>s+x.value,0),cost=rows.reduce((s,x)=>s+x.cost,0),cash=num(raw?.cash),total=holdingsValue+cash,pnl=holdingsValue-cost;
  const concentrations=rows.slice().sort((a,b)=>b.value-a.value).map(x=>({ticker:x.ticker,weightPct:total?100*x.value/total:0,value:x.value}));
  const project=(rate,years)=>total*Math.pow(1+rate,years);
  return {cash,holdingsValue,totalValue:total,totalCost:cost,totalPnl:pnl,totalPnlPct:cost?100*pnl/cost:0,holdings:rows,concentrations,illustrativeScenarios:{note:'Illustrative compound-return scenarios only; these are not forecasts.',cautious:{annualRate:.04,oneYear:project(.04,1),threeYears:project(.04,3),fiveYears:project(.04,5)},base:{annualRate:.08,oneYear:project(.08,1),threeYears:project(.08,3),fiveYears:project(.08,5)},strong:{annualRate:.12,oneYear:project(.12,1),threeYears:project(.12,3),fiveYears:project(.12,5)}}};
}
function fallbackPortfolioAnswer(q,p){const top=p.concentrations.slice(0,3).map(x=>`${x.ticker} ${x.weightPct.toFixed(1)}%`).join(', ')||'No holdings',s=p.illustrativeScenarios;return `MOVA portfolio snapshot\n\nCurrent portfolio value: ${money(p.totalValue)} (${money(p.holdingsValue)} invested + ${money(p.cash)} cash). Unrealised P/L versus recorded average cost: ${p.totalPnl>=0?'+':''}${money(p.totalPnl)} (${p.totalPnlPct>=0?'+':''}${p.totalPnlPct.toFixed(1)}%).\n\nLargest concentrations: ${top}. Concentration matters because a small number of large positions can dominate both upside and drawdown risk.\n\nIllustrative growth scenarios (not forecasts):\n• 4% annualised: ${money(s.cautious.oneYear)} in 1y, ${money(s.cautious.threeYears)} in 3y, ${money(s.cautious.fiveYears)} in 5y.\n• 8% annualised: ${money(s.base.oneYear)} in 1y, ${money(s.base.threeYears)} in 3y, ${money(s.base.fiveYears)} in 5y.\n• 12% annualised: ${money(s.strong.oneYear)} in 1y, ${money(s.strong.threeYears)} in 3y, ${money(s.strong.fiveYears)} in 5y.\n\nThese scenarios illustrate compounding only; they are not predictions.`;}

const MOVA_COMPANY_NAMES={NVDA:'NVIDIA',MSFT:'Microsoft',AAPL:'Apple',AMZN:'Amazon',META:'Meta Platforms',GOOGL:'Alphabet',GOOG:'Alphabet',TSLA:'Tesla',AVGO:'Broadcom',AMD:'Advanced Micro Devices',ASML:'ASML Holding',PLTR:'Palantir Technologies',NFLX:'Netflix',INTC:'Intel',MU:'Micron Technology',ARM:'Arm Holdings',QCOM:'Qualcomm',ORCL:'Oracle',CRM:'Salesforce',ADBE:'Adobe',TSM:'Taiwan Semiconductor Manufacturing',KLAC:'KLA',LRCX:'Lam Research',AMAT:'Applied Materials'};
const MOVA_TICKER_STOP=new Set(['MOVA','AI','ETF','ETFS','USD','US','UK','CEO','CFO','EPS','PE','P','L','IPO','ADR','THE','AND','WHAT','WHO','WHY','HOW','IS','ARE','MY']);
function inferTicker(q){const raw=String(q||'');for(const [ticker,name] of Object.entries(MOVA_COMPANY_NAMES)){if(new RegExp('\\b'+name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\b','i').test(raw))return ticker;}const tokens=raw.match(/\b[A-Z][A-Z0-9.\-]{1,7}\b/g)||[];return tokens.find(x=>!MOVA_TICKER_STOP.has(x))||'';}
function isPortfolioIntent(q){const x=String(q||'').toLowerCase();return /\bportfolio\b|\bholdings?\b|\bpositions?\b|\ballocation\b|\bconcentration\b|\bdiversif|\bunrealised\b|\bp\/?l\b/.test(x)||/\b(my|our)\s+(investments?|stocks?|shares?)\b/.test(x);}
function pct(v){return Number.isFinite(v)?`${v>=0?'+':''}${v.toFixed(1)}%`:'n/a';}
function histStats(values){const rows=safeArray(values).map(v=>({date:v?.datetime,close:Number(v?.close),high:Number(v?.high),low:Number(v?.low)})).filter(v=>Number.isFinite(v.close));if(!rows.length)return null;const latest=rows[0].close,ret=i=>rows[i]?.close?((latest/rows[i].close)-1)*100:null,yr=rows.slice(0,253),highs=yr.map(x=>x.high).filter(Number.isFinite),lows=yr.map(x=>x.low).filter(Number.isFinite);return {latest,date:rows[0].date,oneMonth:ret(21),threeMonth:ret(63),sixMonth:ret(126),oneYear:ret(252),high52:highs.length?Math.max(...highs):null,low52:lows.length?Math.min(...lows):null,rows};}
async function jsonOrNull(url){try{const r=await fetch(url,{headers:{Accept:'application/json'}});const raw=await r.text();let d=null;try{d=raw?JSON.parse(raw):null;}catch{return null;}return r.ok&&d&&!d.error?d:null;}catch{return null;}}
function profileTimeline(profile){if(Array.isArray(profile?.timeline))return profile.timeline;if(Array.isArray(profile?.history))return profile.history;if(Array.isArray(profile?.milestones))return profile.milestones;return [];}
function newsItems(news){return Array.isArray(news?.items)?news.items:Array.isArray(news?.articles)?news.articles:[];}
function companySummary(profile){return profile?.summary||profile?.overview||profile?.description||profile?.intro||'';}
function companyBusiness(profile){return profile?.sections?.business||profile?.business||profile?.businessModel||profile?.products||'';}
function companyOrigins(profile){return profile?.sections?.origins||profile?.origins||profile?.historySummary||'';}
function companyHighlights(profile){return safeArray(profile?.highlights||profile?.sections?.highlights).map(x=>safeText(x,280)).filter(Boolean).slice(0,6);}
function newsWhyItMatters(item,ticker){const t=`${item?.title||item?.headline||''} ${item?.summary||item?.body||''}`.toLowerCase();if(/tariff|export|sanction|china|trade restriction|geopolit/.test(t))return `Trade or geopolitical policy can change ${ticker}'s addressable market, customer demand and valuation expectations.`;if(/earnings|guidance|revenue|margin|forecast|outlook|profit/.test(t))return `Earnings and guidance can quickly reset growth, margin and valuation expectations for ${ticker}.`;if(/ai|artificial intelligence|data cent|chip|semiconductor|foundry|capex/.test(t))return `This can affect semiconductor/AI demand expectations, customer spending and the growth narrative around ${ticker}.`;if(/acquisition|merger|deal|partnership|contract|order|backlog/.test(t))return `Orders, contracts and strategic deals can change future revenue visibility and investor confidence in ${ticker}.`;if(/analyst|price target|rating|upgrade|downgrade/.test(t))return `Analyst revisions can influence near-term sentiment, although they do not change the underlying business by themselves.`;return `This may influence sentiment, demand expectations or the risk/reward investors assign to ${ticker}.`;}
function isSemiContext(profile,heads,name){const t=`${name} ${profile?.industry||''} ${profile?.description||''} ${companyBusiness(profile)} ${heads.map(x=>x?.title||x?.headline||'').join(' ')}`.toLowerCase();return /semiconductor|chip|lithograph|wafer|foundry|asml|nvidia|amd|broadcom|micron/.test(t);}
function buildWatchList(ticker,semi){const base=[{title:'Earnings & guidance',detail:'Watch whether revenue, margins and management guidance are improving or weakening versus expectations.'},{title:'Demand & order trends',detail:'Look for changes in customer demand, backlog, cancellations, capacity plans or product mix.'},{title:'Valuation vs. growth',detail:'A strong business can still be a poor entry if expectations already price in exceptional growth.'},{title:'Price & momentum',detail:'Track whether price strength is confirmed by improving fundamentals or whether momentum is fading.'}];if(semi)base.splice(2,0,{title:'AI / semiconductor capex',detail:'Monitor hyperscaler, foundry and chipmaker capital spending because it can materially affect equipment and semiconductor demand.'});if(semi)base.splice(3,0,{title:'Export controls & geopolitics',detail:'New restrictions involving China, advanced chips or semiconductor equipment can affect accessible revenue and supply chains.'});return base.slice(0,6);}
function buildBullBear({ticker,profile,h,asset,heads,semi}){const highlights=companyHighlights(profile),bull=[],bear=[];for(const x of highlights.slice(0,3))bull.push({title:'Business strength',detail:x});if(Number.isFinite(h?.oneYear)&&h.oneYear>20)bull.push({title:'Long-term price strength',detail:`The shares are approximately ${pct(h.oneYear)} over the returned 1-year history, showing strong investor demand over that period.`});if(Number.isFinite(h?.sixMonth)&&h.sixMonth>10)bull.push({title:'Medium-term momentum',detail:`The returned 6-month performance is about ${pct(h.sixMonth)}, suggesting the longer trend has remained constructive.`});if(semi)bull.push({title:'Structural demand theme',detail:'AI, advanced computing and semiconductor investment can support long-run demand when customers continue increasing capacity and technology spending.'});if(!bull.length)bull.push({title:'Potential upside',detail:`Upside would improve if ${ticker} delivers stronger growth, margins, guidance or demand than the market currently expects.`});const change=Number(asset?.changePct);if(Number.isFinite(change)&&change<0)bear.push({title:'Near-term weakness',detail:`The latest session move is ${pct(change)}, so current price action is under pressure even if the longer-term trend is stronger.`});if(Number.isFinite(h?.oneYear)&&h.oneYear>60)bear.push({title:'Expectation risk after a strong run',detail:`A roughly ${pct(h.oneYear)} 1-year rise can leave less room for disappointment if growth or guidance slows.`});if(semi)bear.push({title:'Policy / export risk',detail:'Export controls, tariffs and geopolitical restrictions can affect semiconductor demand, customer access and supply chains.'});if(heads.some(x=>/tariff|export|china|sanction/i.test(`${x?.title||''} ${x?.headline||''}`)))bear.push({title:'Current policy catalyst',detail:'Recent headlines include trade-policy or restriction risk, which can increase volatility and alter revenue expectations.'});bear.push({title:'Execution & cycle risk',detail:'Demand can weaken, customers can delay spending, and margins or guidance can disappoint even for high-quality businesses.'});return {bull:bull.slice(0,4),bear:bear.slice(0,4)};}

async function buildCompanyResearch(request,question){
  const ticker=inferTicker(question);if(!ticker)return null;
  const name=MOVA_COMPANY_NAMES[ticker]||ticker,origin=new URL(request.url).origin;
  const [profile,market,history,news]=await Promise.all([jsonOrNull(`${origin}/api/company-history?ticker=${encodeURIComponent(ticker)}&name=${encodeURIComponent(name)}`),jsonOrNull(`${origin}/api/market?symbols=${encodeURIComponent(ticker)}`),jsonOrNull(`${origin}/api/history?symbol=${encodeURIComponent(ticker)}&interval=1day&outputsize=260`),jsonOrNull(`${origin}/api/news?symbols=${encodeURIComponent(ticker)}`)]);
  if(!profile&&!market&&!history&&!news)return null;
  const asset=safeArray(market?.assets)[0]||null,h=histStats(history?.values),heads=newsItems(news).slice(0,6),timeline=profileTimeline(profile).slice(0,7),semi=isSemiContext(profile,heads,name),sources=[];
  if(profile?.website)sources.push({title:`${name} official website`,url:safeText(profile.website,800),kind:'company'});
  const newsCards=heads.map(x=>{const url=safeText(x?.url||'',900),card={title:safeText(x?.title||x?.headline||'Company update',300),source:safeText(x?.source||'News',100),date:safeDate(x?.datetime||x?.publishedAt||x?.date),url,summary:safeText(x?.summary||x?.body||'',360),whyItMatters:newsWhyItMatters(x,ticker)};if(url&&!sources.some(y=>y.url===url))sources.push({title:card.title,url,kind:'news',source:card.source,date:card.date});return card;});
  const price=Number(asset?.priceNative??asset?.priceUSD??asset?.price),changePct=Number(asset?.changePct);
  const performance=h?[{label:'1M',value:h.oneMonth},{label:'3M',value:h.threeMonth},{label:'6M',value:h.sixMonth},{label:'1Y',value:h.oneYear}].filter(x=>Number.isFinite(x.value)):[];
  const historySeries=h?safeArray(h.rows).slice(0,90).reverse().map(x=>({date:safeText(x.date,40),close:x.close})).filter(x=>Number.isFinite(x.close)):[];
  const bullBear=buildBullBear({ticker,profile,h,asset,heads,semi});
  const research={type:'company',ticker,company:{name,summary:safeText(companySummary(profile),2400),business:safeText(companyBusiness(profile),1800),origins:safeText(companyOrigins(profile),1500),industry:safeText(profile?.industry||profile?.description||'',220),founded:safeText(profile?.foundedDisplay||profile?.founded||'',120),headquarters:safeText(profile?.headquarters||'',220),website:safeText(profile?.website||'',900)},snapshot:{price:Number.isFinite(price)?price:null,changePct:Number.isFinite(changePct)?changePct:null,direction:safeText(asset?.analysis?.direction||'mixed',80),momentum:safeText(asset?.analysis?.momentum||'normal',80),provider:safeText(asset?.provider||market?.source||'MOVA market feed',100),date:safeDate(h?.date||new Date())},performance,range52:h&&Number.isFinite(h.low52)&&Number.isFinite(h.high52)?{low:h.low52,high:h.high52,latest:h.latest}:null,historySeries,bullCase:bullBear.bull,bearCase:bullBear.bear,milestones:timeline.map(x=>({year:safeText(x?.year||'',30),title:safeText(x?.title||'Company milestone',180),detail:safeText(x?.text||x?.description||'',520)})),news:newsCards,watchNext:buildWatchList(ticker,semi),highlights:companyHighlights(profile)};
  const answerParts=[`${name} (${ticker}) — MOVA research overview.`];if(research.company.summary)answerParts.push(`Who they are: ${research.company.summary}`);if(research.company.business)answerParts.push(`How the business works: ${research.company.business}`);if(h){const moves=performance.map(x=>`${x.label} ${pct(x.value)}`).join(', ');answerParts.push(`Share-price history: latest returned close ${money(h.latest)}${h.date?` on ${safeText(h.date,40)}`:''}${moves?`; performance ${moves}`:''}${research.range52?`; 52-week range ${money(research.range52.low)} to ${money(research.range52.high)}`:''}.`);}if(asset)answerParts.push(`Current market read: ${ticker} is ${Number.isFinite(changePct)?pct(changePct):'little changed'} on the latest session${Number.isFinite(price)?` at about ${money(price)}`:''}. MOVA classifies the direction as ${research.snapshot.direction} with ${research.snapshot.momentum} momentum.`);if(newsCards.length)answerParts.push(`Recent catalysts: ${newsCards.slice(0,3).map(n=>n.title).join(' | ')}.`);answerParts.push(`What matters next: earnings and guidance, demand/order trends, valuation versus growth, current price momentum${semi?', semiconductor capital spending and export-policy developments':''}.`);
  return {answer:answerParts.join('\n\n'),sources:sources.slice(0,12),research};
}

function collectSources(data){const out=[];for(const item of safeArray(data?.output)){if(item?.type==='web_search_call')for(const s of safeArray(item?.action?.sources)){const url=s?.url||s?.link,title=s?.title||s?.name||url;if(url&&!out.some(x=>x.url===url))out.push({title:safeText(title,180),url:safeText(url,800),kind:'web'});}if(item?.type==='message')for(const c of safeArray(item?.content))for(const a of safeArray(c?.annotations)){const url=a?.url||a?.url_citation?.url,title=a?.title||a?.url_citation?.title||url;if(url&&!out.some(x=>x.url===url))out.push({title:safeText(title,180),url:safeText(url,800),kind:'web'});}}return out.slice(0,12);}
function mergeSources(...groups){const out=[];for(const g of groups)for(const s of safeArray(g)){if(s?.url&&!out.some(x=>x.url===s.url))out.push(s);}return out.slice(0,14);}

export default {async fetch(request){
  if(request.method==='GET')return Response.json({ok:true,configured:Boolean(process.env.OPENAI_API_KEY),model:'gpt-5.6-terra'},{headers:{'Cache-Control':'no-store'}});
  if(request.method!=='POST')return Response.json({error:'Method not allowed'},{status:405});
  try{
    const body=await request.json(),question=safeText(body?.question,5000).trim();if(!question)return Response.json({error:'Ask a question first.'},{status:400});
    const portfolio=portfolioSummary(body?.portfolio||{}),history=safeArray(body?.history).slice(-8).map(x=>({role:x?.role==='assistant'?'assistant':'user',content:safeText(x?.content,4000)}));
    const companyResearch=await buildCompanyResearch(request,question),key=process.env.OPENAI_API_KEY;
    if(!key){
      if(isPortfolioIntent(question))return Response.json({answer:fallbackPortfolioAnswer(question,portfolio),sources:[],configured:false,portfolio,research:{type:'portfolio',totalValue:portfolio.totalValue,cash:portfolio.cash,totalPnl:portfolio.totalPnl,totalPnlPct:portfolio.totalPnlPct,concentrations:portfolio.concentrations.slice(0,8),scenarios:portfolio.illustrativeScenarios}},{headers:{'Cache-Control':'no-store'}});
      if(companyResearch)return Response.json({...companyResearch,configured:false,ticker:companyResearch.research?.ticker,fallback:'company-research'},{headers:{'Cache-Control':'no-store'}});
      return Response.json({answer:'MOVA can research named companies and tickers from its current market/company feeds. Include a ticker such as ASML, AMD or NVDA. Connecting OPENAI_API_KEY enables broader conversational synthesis and live web research.',sources:[],configured:false},{headers:{'Cache-Control':'no-store'}});
    }
    const now=new Date().toISOString();
    const instructions=`You are MOVA AI, the research assistant inside MOVA Trading. Current timestamp: ${now}.\n\nAnswer questions about stocks, shares, ETFs, indices, commodities, market drivers, news and the user's supplied MOVA portfolio.\n\nFor any question naming a stock, share, ticker, listed company, ETF, index or commodity, use web search so the answer reflects current information even when the user does not explicitly say latest or current. Prefer primary/company filings, investor relations, exchanges, regulators and established financial/news sources. State dates for current news. Distinguish facts from interpretation. Never invent prices, analyst targets, earnings numbers or headlines.\n\nFor company research, go beyond a short summary. Explain what the business does and how it makes money; important investment/share-price history and turning points; current price trend and momentum; earnings, growth, margins or valuation context when reliably available; the bull case and what would need to go right; the bear case, material risks and what could invalidate the thesis; recent news/catalysts and WHY each item matters; competitive, sector and macro factors; and exactly what investors should monitor next.\n\nFor portfolio questions, analyse supplied holdings, weights, average costs, P/L and cash. Identify concentration, diversification, correlated exposures, company/sector/macro risks, catalysts and what could materially change the outlook. If asked for projected growth, use scenario analysis and clearly label assumptions; never present a projection as guaranteed.\n\nStyle: plain English for a visual learner. Be detailed enough to teach, normally around 700–1200 words for a broad company/investment-history question, but stay focused. Lead with a direct MOVA view, then use short clearly named sections. Explain WHY data matters instead of only listing it. Avoid generic filler.`;
    const context={question,portfolio,conversation:history,movaCompanyResearch:companyResearch?.research||null};
    const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-5.6-terra',reasoning:{effort:'medium'},text:{verbosity:'high'},tools:[{type:'web_search_preview',search_context_size:'high'}],tool_choice:'auto',include:['web_search_call.action.sources'],store:false,max_output_tokens:9000,instructions,input:[{role:'user',content:[{type:'input_text',text:`MOVA context (JSON):\n${JSON.stringify(context)}\n\nAnswer the user's question using this context and current web research.`}]}]})});
    const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(errorText(data?.error)||`OpenAI ${r.status}`);
    const answer=safeText(data?.output_text||'',36000)||safeArray(data?.output).flatMap(i=>safeArray(i?.content)).filter(c=>c?.type==='output_text').map(c=>c.text).join('\n').trim();if(!answer)throw new Error('AI returned no text response');
    return Response.json({answer,sources:mergeSources(companyResearch?.sources,collectSources(data)),configured:true,model:data?.model||'gpt-5.6-terra',asOf:now,portfolio,research:companyResearch?.research||null},{headers:{'Cache-Control':'no-store'}});
  }catch(e){return Response.json({error:errorText(e)},{status:500,headers:{'Cache-Control':'no-store'}});}
}};
