function text(v){return String(v??'').trim()}
function clean(v){return text(v).replace(/\s+/g,' ').trim()}
function sentences(v){return clean(v).match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[]}
function yearFromTime(v){const m=text(v).match(/[+-]?(\d{4,})-/);return m?String(Number(m[1])):''}
function claimIds(e,p){return(e?.claims?.[p]||[]).map(c=>c?.mainsnak?.datavalue?.value?.id).filter(Boolean)}
function claimTime(e,p){return(e?.claims?.[p]||[]).map(c=>c?.mainsnak?.datavalue?.value?.time).find(Boolean)||''}
function claimString(e,p){return(e?.claims?.[p]||[]).map(c=>c?.mainsnak?.datavalue?.value).find(v=>typeof v==='string')||''}
async function fetchJson(url,timeout=5000){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),timeout);try{const r=await fetch(url,{signal:ctrl.signal,headers:{Accept:'application/json'}});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();if(d?.error)throw new Error(d.error.info||d.error.code||'API error');return d}finally{clearTimeout(timer)}}
async function wikiSearch(name){const u=new URL('https://en.wikipedia.org/w/api.php');u.searchParams.set('action','query');u.searchParams.set('list','search');u.searchParams.set('srsearch',name+' company');u.searchParams.set('srlimit','5');u.searchParams.set('format','json');u.searchParams.set('origin','*');const d=await fetchJson(u),rows=d?.query?.search||[],good=rows.find(x=>/company|corporation|technology|automotive|bank|semiconductor|software|energy|manufacturer|retail/i.test((x.title||'')+' '+(x.snippet||'')));return(good||rows[0])?.title||name}
function decodeHtml(s){return String(s||'').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16))).replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>')}
function htmlToText(html){let s=String(html||'');s=s.replace(/<sup\b[\s\S]*?<\/sup>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<table\b[\s\S]*?<\/table>/gi,' ').replace(/<figure\b[\s\S]*?<\/figure>/gi,' ');s=s.replace(/<\/(?:p|li|h[1-6]|div|section)>/gi,'. ').replace(/<br\s*\/?\s*>/gi,'. ').replace(/<[^>]+>/g,' ');s=decodeHtml(s).replace(/\[[0-9]+\]/g,' ');const cut=s.search(/\bReferences\b|\bExternal links\b|\bSee also\b/i);if(cut>5000)s=s.slice(0,cut);return clean(s)}
async function wikiPage(title){const q=new URL('https://en.wikipedia.org/w/api.php');q.searchParams.set('action','query');q.searchParams.set('prop','extracts|pageprops');q.searchParams.set('explaintext','1');q.searchParams.set('exsentences','4');q.searchParams.set('redirects','1');q.searchParams.set('titles',title);q.searchParams.set('format','json');q.searchParams.set('origin','*');const p=new URL('https://en.wikipedia.org/w/api.php');p.searchParams.set('action','parse');p.searchParams.set('page',title);p.searchParams.set('prop','text');p.searchParams.set('format','json');p.searchParams.set('origin','*');const[qd,pd]=await Promise.all([fetchJson(q,5000),fetchJson(p,6500)]);const page=Object.values(qd?.query?.pages||{})[0]||{},summary=clean(page.extract||''),full=htmlToText(pd?.parse?.text?.['*']||'');return{title:pd?.parse?.title||page.title||title,summary,full,wikibase:page?.pageprops?.wikibase_item||''}}
async function wikidata(id){if(!id)return null;const u=new URL('https://www.wikidata.org/w/api.php');u.searchParams.set('action','wbgetentities');u.searchParams.set('ids',id);u.searchParams.set('props','labels|descriptions|claims');u.searchParams.set('languages','en');u.searchParams.set('format','json');u.searchParams.set('origin','*');const d=await fetchJson(u,4500);return d?.entities?.[id]||null}
async function labels(ids){const unique=[...new Set(ids.filter(Boolean))];if(!unique.length)return{};const u=new URL('https://www.wikidata.org/w/api.php');u.searchParams.set('action','wbgetentities');u.searchParams.set('ids',unique.slice(0,30).join('|'));u.searchParams.set('props','labels');u.searchParams.set('languages','en');u.searchParams.set('format','json');u.searchParams.set('origin','*');const d=await fetchJson(u,4000),out={};for(const[id,e]of Object.entries(d?.entities||{}))out[id]=e?.labels?.en?.value||id;return out}
function titleFor(s){if(/launch|introduced|released|unveiled|debut/i.test(s))return'Product / launch milestone';if(/acquir|merged|purchas/i.test(s))return'Acquisition / corporate milestone';if(/expanded|opened|built|production|factory|plant|manufactur/i.test(s))return'Expansion / production milestone';if(/listed|public|IPO|stock exchange/i.test(s))return'Public-market milestone';if(/founded|established|incorporated|formed/i.test(s))return'Founded / established';if(/CEO|chief executive|chairman|leadership/i.test(s))return'Leadership milestone';if(/AI|artificial intelligence|GPU|CPU|cloud|data cent|memory|semiconductor/i.test(s))return'Technology milestone';return'Company milestone'}
function compactEvent(s,y){let t=clean(s);if(t.length>250)t=t.slice(0,247).replace(/\s+\S*$/,'')+'…';if(!t.includes(y))t=y+' — '+t;return t}
function pickContext(s,y){const clauses=s.split(/;|\.(?=\s+[A-Z])|,(?=\s+(?:and\s+)?(?:in\s+)?(?:19|20)\d{2}\b)/).map(clean).filter(Boolean);return clauses.find(c=>c.includes(y))||s}
function timelineFrom(full,name,founded){const out=[],seen=new Set();if(founded){out.push({year:founded,title:'Founded / established',text:name+' was founded or established in '+founded+'.'});seen.add(founded)}const key=/(launch|introduced|released|began|opened|acquired|expanded|announced|became|listed|public|production|delivered|developed|moved|renamed|merged|built|started|unveiled|founded|established|incorporated|formed|CEO|chief executive|chairman|factory|plant|manufactur|AI|artificial intelligence|GPU|CPU|cloud|data cent|memory|semiconductor)/i;for(const s of sentences(full)){if(s.length<24||s.length>700||!key.test(s))continue;const years=[...new Set(s.match(/\b(?:19|20)\d{2}\b/g)||[])];for(const y of years){if(seen.has(y))continue;const c=pickContext(s,y);out.push({year:y,title:titleFor(c),text:compactEvent(c,y)});seen.add(y);if(out.length>=14)break}if(out.length>=14)break}return out.sort((a,b)=>Number(a.year)-Number(b.year)).slice(0,14)}
function pickSection(full,re,max=4){const rows=sentences(full).filter(s=>s.length>35&&s.length<450&&re.test(s));return rows.slice(0,max).join(' ')}
export default{async fetch(request){if(request.method!=='GET')return Response.json({error:'Method not allowed'},{status:405});const u=new URL(request.url),ticker=text(u.searchParams.get('ticker')).toUpperCase(),name=text(u.searchParams.get('name'))||ticker;if(!name)return Response.json({error:'Company name required'},{status:400});let title=name,summary='',full='',entity=null,sourceStatus=[];try{title=await wikiSearch(name);sourceStatus.push('Wikipedia search')}catch(e){}try{const page=await wikiPage(title);title=page.title;summary=page.summary;full=page.full;sourceStatus.push('Wikipedia summary + full company article');if(page.wikibase)entity=await wikidata(page.wikibase)}catch(e){}let founded='',founders=[],headquarters='',website='',description='';if(entity){try{founded=yearFromTime(claimTime(entity,'P571'));const founderIds=claimIds(entity,'P112'),hqIds=claimIds(entity,'P159'),map=await labels([...founderIds,...hqIds]);founders=founderIds.map(id=>map[id]).filter(Boolean);headquarters=hqIds.map(id=>map[id]).filter(Boolean).join('; ');website=claimString(entity,'P856');description=entity?.descriptions?.en?.value||'';sourceStatus.push('Wikidata facts')}catch(e){}}const timeline=timelineFrom(full,name,founded),origins=pickSection(full,/(founded|established|incorporated|formed|started|early history|began operations)/i,3)||summary,business=pickSection(full,/(develops|designs|manufactures|produces|operates|provides|sells|services|products|business|cloud|advertising|software|hardware|vehicles|semiconductor|memory)/i,4)||summary;return Response.json({ticker,name,title,description,founded,foundedDisplay:founded,founders,headquarters,website,summary,sections:{origins,business,development:'',products:'',recent:''},highlights:timeline.slice(0,8),revenueContext:{summary:'',items:[],note:'MOVA does not invent segment percentages when a verified source does not provide them.'},timeline,partial:!(summary&&timeline.length>2),sourceLabel:sourceStatus.length?sourceStatus.join(' + '):'Company reference sources temporarily unavailable'},{headers:{'Cache-Control':'public, s-maxage=3600, stale-while-revalidate=21600'}})}};