function text(v){return String(v??'').trim()}
function clean(v){return text(v).replace(/\s+/g,' ').trim()}
function sentences(v){return clean(v).match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[]}
function yearFromTime(v){const m=text(v).match(/[+-]?(\d{4,})-/);return m?String(Number(m[1])):''}
function claimIds(e,p){return(e?.claims?.[p]||[]).map(c=>c?.mainsnak?.datavalue?.value?.id).filter(Boolean)}
function claimTime(e,p){return(e?.claims?.[p]||[]).map(c=>c?.mainsnak?.datavalue?.value?.time).find(Boolean)||''}
function claimString(e,p){return(e?.claims?.[p]||[]).map(c=>c?.mainsnak?.datavalue?.value).find(v=>typeof v==='string')||''}
async function fetchJson(url,timeout=4500){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),timeout);try{const r=await fetch(url,{signal:ctrl.signal,headers:{Accept:'application/json'}});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(timer)}}
async function wikiSearch(name){const u=new URL('https://en.wikipedia.org/w/api.php');u.searchParams.set('action','query');u.searchParams.set('list','search');u.searchParams.set('srsearch',name+' company');u.searchParams.set('srlimit','5');u.searchParams.set('format','json');u.searchParams.set('origin','*');const d=await fetchJson(u),rows=d?.query?.search||[],good=rows.find(x=>/company|corporation|technology|automotive|bank|semiconductor|software|energy|manufacturer|retail/i.test((x.title||'')+' '+(x.snippet||'')));return(good||rows[0])?.title||name}
async function wikiPage(title){const u=new URL('https://en.wikipedia.org/w/api.php');u.searchParams.set('action','query');u.searchParams.set('prop','extracts|pageprops');u.searchParams.set('explaintext','1');u.searchParams.set('exchars','22000');u.searchParams.set('redirects','1');u.searchParams.set('titles',title);u.searchParams.set('format','json');u.searchParams.set('origin','*');const d=await fetchJson(u,6000),page=Object.values(d?.query?.pages||{})[0]||{},full=clean(page.extract||''),summary=sentences(full).slice(0,3).join(' ');return{title:page.title||title,summary,full,wikibase:page?.pageprops?.wikibase_item||''}}
async function wikidata(id){if(!id)return null;const u=new URL('https://www.wikidata.org/w/api.php');u.searchParams.set('action','wbgetentities');u.searchParams.set('ids',id);u.searchParams.set('props','labels|descriptions|claims');u.searchParams.set('languages','en');u.searchParams.set('format','json');u.searchParams.set('origin','*');const d=await fetchJson(u);return d?.entities?.[id]||null}
async function labels(ids){const unique=[...new Set(ids.filter(Boolean))];if(!unique.length)return{};const u=new URL('https://www.wikidata.org/w/api.php');u.searchParams.set('action','wbgetentities');u.searchParams.set('ids',unique.slice(0,30).join('|'));u.searchParams.set('props','labels');u.searchParams.set('languages','en');u.searchParams.set('format','json');u.searchParams.set('origin','*');const d=await fetchJson(u),out={};for(const[id,e]of Object.entries(d?.entities||{}))out[id]=e?.labels?.en?.value||id;return out}
function titleFor(s){if(/launch|introduced|released|unveiled|debut/i.test(s))return'Product / launch milestone';if(/acquir|merged|purchas/i.test(s))return'Acquisition / corporate milestone';if(/expanded|opened|built|production|factory|plant|manufactur/i.test(s))return'Expansion / production milestone';if(/listed|public|IPO|stock exchange/i.test(s))return'Public-market milestone';if(/founded|established|incorporated/i.test(s))return'Founded / established';if(/CEO|chief executive|chairman|leadership/i.test(s))return'Leadership milestone';return'Company milestone'}
function compactEvent(s,y){let t=clean(s);if(t.length>240)t=t.slice(0,237).replace(/\s+\S*$/,'')+'…';if(!t.includes(y))t=y+' — '+t;return t}
function timelineFrom(full,name,founded){const out=[],seen=new Set();if(founded){out.push({year:founded,title:'Founded / established',text:name+' was founded or established in '+founded+'.'});seen.add(founded)}
  for(const s of sentences(full)){
    if(s.length<28)continue;
    if(!/(launch|introduced|released|began|opened|acquired|expanded|announced|became|listed|public|production|delivered|developed|moved|renamed|merged|built|started|unveiled|founded|established|incorporated|CEO|chief executive|chairman|factory|plant|manufactur)/i.test(s))continue;
    const years=[...new Set(s.match(/\b(?:19|20)\d{2}\b/g)||[])];
    if(!years.length)continue;
    const clauses=s.split(/;|\.(?=\s+[A-Z])/).map(clean).filter(Boolean);
    for(const y of years){
      if(seen.has(y))continue;
      const clause=clauses.find(c=>c.includes(y))||s;
      out.push({year:y,title:titleFor(clause),text:compactEvent(clause,y)});seen.add(y);
      if(out.length>=12)break;
    }
    if(out.length>=12)break;
  }
  return out.sort((a,b)=>Number(a.year)-Number(b.year)).slice(0,12)
}
export default{async fetch(request){if(request.method!=='GET')return Response.json({error:'Method not allowed'},{status:405});const u=new URL(request.url),ticker=text(u.searchParams.get('ticker')).toUpperCase(),name=text(u.searchParams.get('name'))||ticker;if(!name)return Response.json({error:'Company name required'},{status:400});let title=name,summary='',full='',entity=null,sourceStatus=[];try{title=await wikiSearch(name);sourceStatus.push('Wikipedia search')}catch(e){}try{const page=await wikiPage(title);title=page.title;summary=page.summary;full=page.full;sourceStatus.push('Wikipedia company article');if(page.wikibase)entity=await wikidata(page.wikibase)}catch(e){}let founded='',founders=[],headquarters='',website='',description='';if(entity){try{founded=yearFromTime(claimTime(entity,'P571'));const founderIds=claimIds(entity,'P112'),hqIds=claimIds(entity,'P159'),map=await labels([...founderIds,...hqIds]);founders=founderIds.map(id=>map[id]).filter(Boolean);headquarters=hqIds.map(id=>map[id]).filter(Boolean).join('; ');website=claimString(entity,'P856');description=entity?.descriptions?.en?.value||'';sourceStatus.push('Wikidata facts')}catch(e){}}const timeline=timelineFrom(full,name,founded);return Response.json({ticker,name,title,description,founded,foundedDisplay:founded,founders,headquarters,website,summary,sections:{origins:summary,business:summary,development:'',products:'',recent:''},highlights:timeline.slice(0,6),revenueContext:{summary:'',items:[],note:'MOVA does not invent segment percentages when a verified source does not provide them.'},timeline,partial:!(summary&&founded&&founders.length&&headquarters),sourceLabel:sourceStatus.length?sourceStatus.join(' + '):'Company reference sources temporarily unavailable'},{headers:{'Cache-Control':'public, s-maxage=21600, stale-while-revalidate=86400'}})}};