const STOCKS=new Set(["NVDA","MSFT","AAPL","AMZN","META","GOOGL","TSLA","AVGO","QQQ"]);
function alias(raw){let s=String(raw||"").trim().toUpperCase();if(s==="NDX")s="QQQ";if(["XAUUSD","XAU/USD"].includes(s))s="GOLD";if(["USOIL","WTI","WTI OIL"].includes(s))s="OIL";return s}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function round(v,d=2){const n=num(v);return n==null?null:Number(n.toFixed(d))}
function pct(a,b){return a!=null&&b!=null&&b!==0?((a-b)/b)*100:null}
async function td(path,params,key){const u=new URL(`https://api.twelvedata.com/${path}`);Object.entries(params||{}).forEach(([k,v])=>u.searchParams.set(k,String(v)));const r=await fetch(u,{headers:{Accept:"application/json",Authorization:`apikey ${key}`}});const d=await r.json().catch(()=>({}));if(!r.ok||d.status==="error"||d.code)throw new Error(d.message||`Twelve Data ${r.status}`);return d}
function providerSymbol(ticker){return ticker==="GOLD"?"XAU/USD":ticker==="OIL"?"WTI":ticker}
async function seriesFor(ticker,interval,outputsize,key){let symbol=providerSymbol(ticker);try{return await td("time_series",{symbol,interval,outputsize,order:"desc"},key)}catch(e){if(ticker==="OIL")return td("time_series",{symbol:"CL1!",interval,outputsize,order:"desc"},key);throw e}}
async function seriesRaw(symbol,interval,outputsize,key){return td("time_series",{symbol,interval,outputsize,order:"desc"},key)}
async function fhNews(symbol,key){if(!key||!STOCKS.has(symbol)||symbol==="QQQ")return[];const to=new Date(),from=new Date(Date.now()-5*86400000),day=d=>d.toISOString().slice(0,10);const u=new URL("https://finnhub.io/api/v1/company-news");u.searchParams.set("symbol",symbol);u.searchParams.set("from",day(from));u.searchParams.set("to",day(to));const r=await fetch(u,{headers:{"X-Finnhub-Token":key}});const d=await r.json().catch(()=>[]);return Array.isArray(d)?d.slice(0,10):[]}
async function fhGeneralNews(key){if(!key)return[];const u=new URL("https://finnhub.io/api/v1/news");u.searchParams.set("category","general");const r=await fetch(u,{headers:{"X-Finnhub-Token":key}});const d=await r.json().catch(()=>[]);return Array.isArray(d)?d.slice(0,50):[]}
function driverFromHeadlines(rows){const text=rows.map(x=>`${x.headline||""} ${x.summary||""}`).join(" ").toLowerCase();const tags=[];if(/earnings|revenue|profit|guidance|forecast/.test(text))tags.push("Earnings / guidance");if(/ai|chip|semiconductor|product|launch/.test(text))tags.push("Product / AI");if(/analyst|rating|upgrade|downgrade|target/.test(text))tags.push("Analyst action");if(/fed|rate|inflation|yield|dollar/.test(text))tags.push("Macro");return tags}
function commodityWhy(ticker,move){if(ticker==="GOLD")return move>=0?"Gold is strengthening. MOVA will test the move against current Treasury-market and US-dollar proxies rather than assuming one macro cause.":"Gold is weaker today. MOVA will test whether Treasury-market and US-dollar proxies are adding pressure or whether Gold is resisting those macro forces.";if(ticker==="OIL")return move>=0?"Crude is strengthening. MOVA will compare the move with session momentum, volume and current supply/demand headlines.":"Crude is weakening. MOVA will compare selling pressure with session momentum, volume and current supply/demand headlines.";return "Commodity pricing is being compared with its recent range and the previous session."}
function baseDriverCopy(label){
 const k=String(label||"").toLowerCase().replace(/[↑↓]/g,"").trim();
 const map={
  "momentum":{effect:"Momentum measures whether buyers or sellers are persistently controlling price.",watch:"Current session direction, recent closes and the 0–100 Stochastic momentum position.",confirm:"Price remains in the same direction while the oscillator and session structure agree.",risk:"Momentum diverges from price or the oscillator leaves an extreme zone with a reversal in price."},
  "volume":{effect:"Volume shows participation. A price move backed by unusually high participation is generally more credible than the same move on thin activity.",watch:"Current volume versus the recent daily average and whether volume expands with the move.",confirm:"Above-average participation continues while price holds direction.",risk:"Price extends while participation fades, increasing false-breakout or exhaustion risk."},
  "ai demand":{effect:"AI demand is not directly observable tick-by-tick, so MOVA uses semiconductor-sector price confirmation plus current company news as a market proxy.",watch:"Semiconductor-sector performance, AI-linked headlines, orders, hyperscaler capex and guidance.",confirm:"The stock and semiconductor proxy strengthen together while company evidence supports AI spending.",risk:"The stock decouples from the sector or news points to capex, order or margin weakness."},
  "product / ai":{effect:"AI/product demand can change revenue and valuation expectations; MOVA treats sector confirmation and company headlines as evidence, not proof of causation.",watch:"Semiconductor-sector performance, launches, adoption, orders and guidance.",confirm:"Sector and stock performance align with supportive measurable company developments.",risk:"Weak adoption, delayed products, competition or falling sector confirmation."},
  "yields":{effect:"Higher Treasury yields usually raise the opportunity cost of non-yielding Gold and can pressure long-duration growth shares. MOVA uses a Treasury ETF as an inverse yield proxy.",watch:"Gold/stock direction versus the 7–10 year Treasury ETF proxy; falling ETF prices generally imply rising yields.",confirm:"The proxy moves in the macro direction expected to support the asset move.",risk:"The relationship breaks down or another driver dominates the asset."},
  "rates":{effect:"Long-term rate expectations affect discount rates and financing costs. MOVA uses the 7–10 year Treasury ETF as an inverse market proxy for yields.",watch:"Treasury ETF direction against growth-stock/index direction.",confirm:"Rates proxy and price behave consistently with the current move.",risk:"Macro data reverses the rates move or equity-specific news overwhelms it."},
  "usd":{effect:"A stronger US dollar often pressures dollar-priced commodities. MOVA uses EUR/USD as an inverse USD proxy: falling EUR/USD generally means a stronger dollar.",watch:"EUR/USD direction versus the commodity move.",confirm:"Currency movement and commodity price align with the expected inverse relationship.",risk:"Physical demand/supply or risk demand overwhelms the currency relationship."},
  "demand":{effect:"Physical demand data is not available from MOVA's market-price feed in real time, so this panel combines live oil price behaviour with current demand-related headlines.",watch:"Oil momentum, volume and news mentioning consumption, growth, transport, refinery demand or demand forecasts.",confirm:"Price strengthens with supportive demand evidence or weakens with deteriorating demand evidence.",risk:"Supply changes dominate or demand headlines reverse."},
  "supply":{effect:"Physical supply is not inferred from price alone. MOVA combines live oil behaviour with current supply/OPEC/inventory/disruption headlines.",watch:"Oil momentum and news on OPEC+, production, inventories, sanctions, outages and disruptions.",confirm:"Price action aligns with evidence of tightening or loosening supply.",risk:"Production or inventories change in the opposite direction or demand becomes dominant."},
  "inventories":{effect:"Inventory changes can signal whether physical oil supply is building or drawing. MOVA uses current inventory-related headlines alongside live price behaviour.",watch:"Current oil move plus inventory and storage headlines.",confirm:"Draw/build evidence aligns with price direction.",risk:"Inventory data is contradicted by production, demand or geopolitical developments."},
  "breadth":{effect:"Breadth tests whether an index move is shared by many large constituents rather than a few leaders.",watch:"A live basket of major Nasdaq constituents, counting advancers and decliners.",confirm:"A larger share of the basket moves with the index.",risk:"Index direction continues while participation narrows."},
  "tech breadth":{effect:"Technology breadth tests whether strength or weakness extends beyond a single mega-cap name.",watch:"A live basket of major technology and Nasdaq constituents.",confirm:"Most constituents participate in the same direction.",risk:"The index is held up by only a few large weights."},
  "large caps":{effect:"Large Nasdaq weights can materially move QQQ because of their index weights.",watch:"QQQ plus a basket of the largest technology/platform constituents.",confirm:"The majority of major weights move with the index.",risk:"Large-weight leadership reverses or breadth deteriorates."},
  "earnings / guidance":{effect:"Earnings and guidance can immediately change expected cash flows and valuation.",watch:"Current company headlines plus price/volume reaction.",confirm:"Price reaction persists and headlines contain measurable estimate/guidance changes.",risk:"The initial reaction fades or later company detail contradicts the interpretation."},
  "analyst action":{effect:"Analyst changes can influence positioning but matter more when tied to estimate changes and confirmed by price.",watch:"Current analyst headlines and the stock's price/volume reaction.",confirm:"Several revisions align and price confirms them.",risk:"The market ignores the call or company data conflicts with it."},
  "macro":{effect:"Macro conditions affect rates, currencies, demand and risk appetite; MOVA combines live price relationships rather than assigning a single cause.",watch:"Asset momentum, Treasury proxy, currency proxy and market headlines.",confirm:"Several independent signals point in the same direction.",risk:"Signals conflict or asset-specific news dominates."}
 };
 return map[k]||map.macro;
}
function classify(move,prevMove,price,priorHigh,priorLow){if(price!=null&&priorHigh!=null&&price>priorHigh)return"breakout";if(move>1&&prevMove<-.3)return"reversal_up";if(move<-1&&prevMove>.3)return"reversal_down";if(move>=2)return"move_up";if(move<=-2)return"move_down";return"watch"}
function ordered(vals){return [...vals].reverse()}
function sessionStats(vals){const latest=vals[0]||{},prev=vals[1]||{};const close=num(latest.close),open=num(latest.open),high=num(latest.high),low=num(latest.low),prevClose=num(prev.close);const vols=vals.slice(1,21).map(v=>num(v.volume)).filter(v=>v!=null&&v>0),avgVol=vols.length?vols.reduce((a,b)=>a+b,0)/vols.length:null,volume=num(latest.volume);return{price:round(close,4),open:round(open,4),high:round(high,4),low:round(low,4),previousClose:round(prevClose,4),changeFromOpenPct:round(pct(close,open)),changeVsPreviousClosePct:round(pct(close,prevClose)),volume:volume==null?null:Math.round(volume),averageVolume20:avgVol==null?null:Math.round(avgVol),volumeVsAveragePct:volume!=null&&avgVol?round(((volume/avgVol)-1)*100):null}}
function stochasticPoints(vals,period=14){const asc=ordered(vals);const out=[];for(let i=period-1;i<asc.length;i++){const window=asc.slice(i-period+1,i+1);const hh=Math.max(...window.map(v=>num(v.high)??num(v.close)??0)),ll=Math.min(...window.map(v=>num(v.low)??num(v.close)??0)),c=num(asc[i].close);if(c==null||!Number.isFinite(hh)||!Number.isFinite(ll)||hh===ll)continue;out.push({date:asc[i].datetime||asc[i].date||String(i),value:round(((c-ll)/(hh-ll))*100,1),close:round(c,4)})}return out}
function pricePoints(vals,max=30){return ordered(vals).slice(-max).map(v=>({date:v.datetime||v.date||"",open:round(v.open,4),high:round(v.high,4),low:round(v.low,4),close:round(v.close,4),volume:num(v.volume)==null?null:Math.round(num(v.volume))}))}
function oscillatorZone(v){if(v==null)return"Unavailable";if(v<20)return"Potentially oversold";if(v>80)return"Potentially overbought";return"Neutral / mid-range"}
function assetName(t){return t==="QQQ"?"Nasdaq 100 / QQQ":t==="GOLD"?"Gold":t==="OIL"?"WTI Oil":t}
async function proxyData(driver,key){const k=String(driver||"").toLowerCase().replace(/[↑↓]/g,"").trim();let cfg=null;if(["yields","rates"].includes(k))cfg={symbol:"IEF",label:"iShares 7–10 Year Treasury ETF",sense:"inverse-yield",note:"IEF is used as an inverse Treasury-yield market proxy: IEF down generally indicates yields up."};else if(k==="usd")cfg={symbol:"EUR/USD",label:"EUR/USD",sense:"inverse-usd",note:"EUR/USD is used as an inverse USD proxy: EUR/USD down generally indicates a stronger US dollar."};else if(["ai demand","product / ai"].includes(k))cfg={symbol:"SMH",label:"VanEck Semiconductor ETF",sense:"same",note:"SMH is used as a semiconductor-sector market proxy for AI/chip demand expectations."};else if(["large caps","tech lead"].includes(k))cfg={symbol:"QQQ",label:"Invesco QQQ",sense:"same",note:"QQQ is used as a large-cap technology/index leadership proxy."};if(!cfg)return null;try{const d=await seriesRaw(cfg.symbol,"1day",7,key),v=Array.isArray(d.values)?d.values:[];if(v.length<2)return null;const s=sessionStats(v);return{...cfg,...s}}catch(e){return{...cfg,error:e.message}}}
async function breadthData(key){const names=["NVDA","MSFT","AAPL","AMZN","META","GOOGL","AVGO","TSLA"];const rows=await Promise.all(names.map(async symbol=>{try{const d=await seriesRaw(symbol,"1day",3,key),v=Array.isArray(d.values)?d.values:[];const s=sessionStats(v);return{symbol,changePct:s.changeVsPreviousClosePct}}catch(e){return{symbol,changePct:null}}}));const valid=rows.filter(x=>x.changePct!=null),adv=valid.filter(x=>x.changePct>0).length,dec=valid.filter(x=>x.changePct<0).length;return{label:"Major Nasdaq constituent breadth",advancing:adv,declining:dec,unchanged:valid.length-adv-dec,participationPct:valid.length?round((Math.max(adv,dec)/valid.length)*100,0):null,rows}}
function relevantGeneralNews(rows,ticker,driver){const k=String(driver||"").toLowerCase();const pattern=ticker==="OIL"||/supply|demand|inventor/.test(k)?/(oil|crude|opec|inventory|inventories|barrel|energy|refiner|refinery|demand|supply)/i:ticker==="GOLD"?/(gold|bullion|treasury|yield|dollar|fed|inflation|rates)/i:/(nasdaq|technology|chip|semiconductor|ai|rates|treasury)/i;return rows.filter(x=>pattern.test(`${x.headline||""} ${x.summary||""}`)).slice(0,5).map(x=>({headline:x.headline||"",summary:x.summary||"",source:x.source||"",url:x.url||"",datetime:x.datetime?new Date(x.datetime*1000).toISOString():null}))}
function relationshipAnalysis(ticker,driver,asset,proxy,breadth,news,osc){const k=String(driver||"").toLowerCase().replace(/[↑↓]/g,"").trim(),assetMove=asset.changeVsPreviousClosePct??asset.changeFromOpenPct??0;let impact="Mixed / needs confirmation",summary="The live evidence is mixed, so MOVA is not assigning a single cause to the current move.",evidence=[];
 evidence.push(`${assetName(ticker)} is ${assetMove>=0?"up":"down"} ${Math.abs(assetMove).toFixed(2)}% versus the previous close${asset.changeFromOpenPct!=null?` and ${asset.changeFromOpenPct>=0?"up":"down"} ${Math.abs(asset.changeFromOpenPct).toFixed(2)}% from today's open`:""}.`);
 if(asset.volumeVsAveragePct!=null)evidence.push(`Current reported volume is ${asset.volumeVsAveragePct>=0?"about "+Math.abs(asset.volumeVsAveragePct).toFixed(0)+"% above":"about "+Math.abs(asset.volumeVsAveragePct).toFixed(0)+"% below"} its recent 20-session average.`);
 if(osc?.value!=null)evidence.push(`14-period Stochastic %K is ${osc.value.toFixed(1)}, placing momentum in the ${osc.zone.toLowerCase()} zone.`);
 if(proxy&&!proxy.error&&proxy.changeVsPreviousClosePct!=null){const p=proxy.changeVsPreviousClosePct;evidence.push(`${proxy.label} is ${p>=0?"up":"down"} ${Math.abs(p).toFixed(2)}% versus its previous close. ${proxy.note}`);if(["yields","rates"].includes(k)){const yieldsRising=p<0;const expectedSupport=ticker==="GOLD"||STOCKS.has(ticker)||ticker==="QQQ"?!yieldsRising:yieldsRising;const aligned=(assetMove>=0)===expectedSupport;impact=aligned?"Live macro relationship supports the move":"Live macro relationship contradicts the move";summary=`The Treasury proxy suggests yields are ${yieldsRising?"rising":"falling"}. That is ${aligned?"consistent":"not fully consistent"} with today's ${assetMove>=0?"rise":"fall"} in ${assetName(ticker)}, so yields ${aligned?"are a plausible contributor":"do not currently explain the move on their own"}.`}
 else if(k==="usd"){const usdStrong=p<0,expectedGoldUp=!usdStrong,aligned=(assetMove>=0)===expectedGoldUp;impact=aligned?"USD relationship supports the move":"USD relationship contradicts the move";summary=`EUR/USD indicates the dollar is ${usdStrong?"stronger":"weaker"} on the latest daily reading. That is ${aligned?"consistent":"in tension"} with Gold's ${assetMove>=0?"rise":"fall"}, so USD ${aligned?"is a plausible contributor":"is not the dominant explanation right now"}.`}
 else if(["ai demand","product / ai","large caps","tech lead"].includes(k)){const aligned=(assetMove>=0)===(p>=0);impact=aligned?"Sector / index confirmation supports the move":"Sector / index confirmation is diverging";summary=`${proxy.label} is ${p>=0?"higher":"lower"} while ${assetName(ticker)} is ${assetMove>=0?"higher":"lower"}. ${aligned?"The same-direction move provides market confirmation.":"The divergence weakens the case that this driver alone is controlling today's price."}`}}
 if(breadth){evidence.push(`${breadth.label}: ${breadth.advancing} advancing, ${breadth.declining} declining across ${breadth.rows.filter(x=>x.changePct!=null).length} tracked major constituents.`);const aligned=assetMove>=0?breadth.advancing>breadth.declining:breadth.declining>breadth.advancing;impact=aligned?"Breadth confirms the index move":"Breadth is not confirming the index move";summary=`Major-constituent breadth is ${breadth.advancing}-${breadth.declining} (advancers-decliners). ${aligned?"Participation is confirming":"Participation is diverging from"} the current ${assetMove>=0?"upward":"downward"} move.`}
 if(["momentum","reversal","pressure"].includes(k)){impact=osc?.value<20?"Momentum is in a potential oversold zone":osc?.value>80?"Momentum is in a potential overbought zone":assetMove>=0?"Positive momentum, not yet extreme":"Negative momentum, not yet extreme";summary=`Today's price is ${assetMove>=0?"advancing":"declining"} and the Stochastic %K is ${osc?.value!=null?osc.value.toFixed(1):"unavailable"}. ${osc?.value<20?"Momentum is stretched on the downside, which can increase reversal risk if price starts to turn up.":osc?.value>80?"Momentum is stretched on the upside, which can increase pullback/reversal risk if price starts to turn down.":"Momentum is between the 20/80 extreme zones, so the oscillator is not flagging an extreme condition."}`}
 if(k==="volume"){impact=asset.volumeVsAveragePct==null?"Volume data unavailable":asset.volumeVsAveragePct>20?"High participation confirms the move":asset.volumeVsAveragePct<-20?"Low participation weakens confirmation":"Participation is near normal";summary=asset.volumeVsAveragePct==null?"The provider did not return comparable volume for this instrument.":`Reported volume is ${Math.abs(asset.volumeVsAveragePct).toFixed(0)}% ${asset.volumeVsAveragePct>=0?"above":"below"} the recent 20-session average. ${Math.abs(asset.volumeVsAveragePct)>=20?"That is meaningful enough to change confidence in today's price move.":"That is close enough to normal that volume is not a strong standalone driver."}`}
 if(["supply","demand","inventories"].includes(k)){impact=news.length?"Live price + current fundamental headlines":"Live price available; fundamental feed limited";summary=`WTI is ${assetMove>=0?"up":"down"} ${Math.abs(assetMove).toFixed(2)}% versus the previous close. ${news.length?`MOVA found ${news.length} current oil-related headline${news.length===1?"":"s"} to use as fundamental context; these are shown below rather than inferring physical supply/demand from price alone.`:"No sufficiently relevant current oil headline was returned, so MOVA will not invent a supply/demand explanation."}`}
 if(["earnings / guidance","analyst action","macro"].includes(k)){if(news.length)evidence.push(`Current contextual headline: ${news[0].headline}`);impact=news.length?"Current news context available":"Price evidence available; no dominant headline";summary=news.length?`The current price move is being assessed alongside ${news.length} relevant recent headline${news.length===1?"":"s"}. MOVA treats those headlines as context and requires price confirmation before attributing the move to them.`:`No dominant current headline was found for this driver, so the panel is relying on measurable price, momentum and volume evidence.`}
 return{impact,summary,evidence}
}
async function driverAnalysis(ticker,driver,tdKey,fhKey){const daily=await seriesFor(ticker,"1day",45,tdKey),vals=Array.isArray(daily.values)?daily.values:[];if(vals.length<15)throw new Error("Not enough history for momentum analysis");const asset=sessionStats(vals),stoch=stochasticPoints(vals,14),latestStoch=stoch.length?stoch[stoch.length-1].value:null,osc={name:"14-period Stochastic %K",value:latestStoch,zone:oscillatorZone(latestStoch),lower:20,upper:80,points:stoch.slice(-30),note:"20 and 80 are normalized momentum thresholds on a 0–100 oscillator. They are not percentages below/above today's opening price."};const k=String(driver||"").toLowerCase().replace(/[↑↓]/g,"").trim();let proxy=null,breadth=null,news=[];if(["breadth","tech breadth"].includes(k)||(ticker==="QQQ"&&k==="large caps"))breadth=await breadthData(tdKey);else proxy=await proxyData(k,tdKey);if(STOCKS.has(ticker)&&ticker!=="QQQ")news=(await fhNews(ticker,fhKey)).slice(0,5).map(x=>({headline:x.headline||"",summary:x.summary||"",source:x.source||"",url:x.url||"",datetime:x.datetime?new Date(x.datetime*1000).toISOString():null}));else if(["supply","demand","inventories","macro","yields","rates","usd"].includes(k))news=relevantGeneralNews(await fhGeneralNews(fhKey),ticker,k);const rel=relationshipAnalysis(ticker,k,asset,proxy,breadth,news,osc),copy=baseDriverCopy(k);return{ticker,name:assetName(ticker),driver:String(driver||"Market driver").replace(/[↑↓]/g,"").trim(),asOf:new Date().toISOString(),asset:{...asset,series:pricePoints(vals,30)},oscillator:osc,proxy,breadth,headlines:news,analysis:{...rel,effect:copy.effect,watch:copy.watch,confirm:copy.confirm,risk:copy.risk},method:"live/near-live market series + normalized momentum + driver proxy/news context"}}
function driverDetail(label,ticker,move){const copy=baseDriverCopy(label);return{label,impact:`${move>=0?"Supporting / positive":"Pressuring / negative"} current move`,summary:`Open this driver for live market evidence, momentum and current contextual data for ${ticker}.`,...copy}}
export default{async fetch(request){if(request.method!=="GET")return Response.json({error:"Method not allowed"},{status:405});const tdKey=process.env.TWELVE_DATA_API_KEY,fh=process.env.FINNHUB_API_KEY;if(!tdKey)return Response.json({error:"TWELVE_DATA_API_KEY is required for AI monitor history"},{status:500});const u=new URL(request.url);if((u.searchParams.get("mode")||"").toLowerCase()==="driver"){try{const ticker=alias(u.searchParams.get("ticker")||""),driver=u.searchParams.get("driver")||"Macro";if(!ticker)return Response.json({error:"ticker is required"},{status:400});return Response.json(await driverAnalysis(ticker,driver,tdKey,fh),{headers:{"Cache-Control":"public, s-maxage=45, stale-while-revalidate=90"}})}catch(e){return Response.json({error:e.message||"Driver analysis failed"},{status:500})}}
 const symbols=(u.searchParams.get("symbols")||"NVDA,QQQ,GOLD,OIL").split(",").map(alias).filter(Boolean).slice(0,10),items=[],errors=[];for(const ticker of symbols){try{const hist=await seriesFor(ticker,"1day",25,tdKey),vals=Array.isArray(hist.values)?hist.values:[];if(vals.length<3)throw new Error("Not enough daily history");const c0=num(vals[0].close),c1=num(vals[1].close),c2=num(vals[2].close),move=c0&&c1?((c0-c1)/c1)*100:0,prevMove=c1&&c2?((c1-c2)/c2)*100:0,prior=vals.slice(1,6).map(v=>num(v.high)||num(v.close)).filter(Number.isFinite),lows=vals.slice(1,6).map(v=>num(v.low)||num(v.close)).filter(Number.isFinite),priorHigh=prior.length?Math.max(...prior):null,priorLow=lows.length?Math.min(...lows):null,signal=classify(move,prevMove,c0,priorHigh,priorLow);let news=[],tags=[];if(STOCKS.has(ticker)&&ticker!=="QQQ"){news=await fhNews(ticker,fh);tags=driverFromHeadlines(news);if(!tags.includes("Momentum"))tags.unshift("Momentum");if(vals[0]?.volume!=null&&!tags.includes("Volume"))tags.splice(1,0,"Volume")}else if(ticker==="QQQ")tags=["Tech breadth","Rates","Large caps"];else tags=ticker==="GOLD"?["Momentum","Yields","USD"]:ticker==="OIL"?["Momentum","Supply","Demand"]:["Macro"];const why=STOCKS.has(ticker)?(tags.length?`${tags.join(", ")} are the main measurable/contextual drivers MOVA is testing. Today's ${move>=0?"gain":"decline"} is ${Math.abs(move)>Math.abs(prevMove)?"stronger":"less pronounced"} than the previous session. Open a driver for live evidence and the 20/80 momentum chart.`:`Today's ${move>=0?"gain":"decline"} is being assessed from price, volume and recent news rather than a narrative guess.`):commodityWhy(ticker,move);const st=stochasticPoints(vals,14),sv=st.length?st[st.length-1].value:null;items.push({ticker,name:assetName(ticker),price:c0,move:round(move),prevMove:round(prevMove),signal,priorHigh,priorLow,stochastic:sv,stochasticZone:oscillatorZone(sv),why,tags:tags.slice(0,4),drivers:tags.slice(0,4).map(t=>driverDetail(t,ticker,move)),confidence:Math.min(90,55+Math.round(Math.min(20,Math.abs(move)*5))+Math.min(12,tags.length*3)),headlines:news.slice(0,3).map(x=>x.headline)});}catch(e){errors.push({ticker,error:e.message})}}return Response.json({asOf:new Date().toISOString(),items,errors,method:"market history + current news + live driver drill-down"},{headers:{"Cache-Control":"public, s-maxage=60, stale-while-revalidate=120"}})}};
