const STOCKS=new Set(["NVDA","MSFT","AAPL","AMZN","META","GOOGL","TSLA","AVGO","QQQ"]);
const NAMES={NVDA:"NVIDIA",MSFT:"Microsoft",AAPL:"Apple",AMZN:"Amazon",META:"Meta Platforms",GOOGL:"Alphabet",TSLA:"Tesla",AVGO:"Broadcom",QQQ:"Nasdaq 100 / QQQ",GOLD:"Gold",SILVER:"Silver",OIL:"WTI Oil"};
const PROXIES={yields:{symbol:"^TNX",label:"US 10Y Treasury yield",note:"Higher yields can pressure long-duration growth shares and non-yielding gold."},usd:{symbol:"DXY",label:"US Dollar Index",note:"A stronger dollar can pressure USD-priced commodities and affect multinational earnings."},rates:{symbol:"^TNX",label:"US 10Y Treasury yield",note:"Rate expectations influence equity valuation multiples."},breadth:{breadth:true,label:"Large-cap technology breadth"},tech:{breadth:true,label:"Large-cap technology breadth"},"ai demand":{breadth:true,label:"AI / mega-cap technology breadth"}};
function num(v){const n=Number(v);return Number.isFinite(n)?n:null;}function clamp(n,a=0,b=100){return Math.max(a,Math.min(b,n));}
function alias(raw){let s=String(raw||"").trim().toUpperCase();if(s==="GOOG")s="GOOGL";if(["XAUUSD","XAU/USD"].includes(s))s="GOLD";if(["XAGUSD","XAG/USD"].includes(s))s="SILVER";if(["USOIL","WTI","WTI OIL","CRUDE OIL"].includes(s))s="OIL";if(["NDX","NASDAQ100","NASDAQ 100"].includes(s))s="QQQ";return s;}
async function finnhub(path,key){const u=new URL(`https://finnhub.io/api/v1/${path}`);u.searchParams.set("token",key);const r=await fetch(u,{headers:{Accept:"application/json"}});const d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw new Error(d.error||`Finnhub ${r.status}`);return d;}
async function twelve(path,params,key){const u=new URL(`https://api.twelvedata.com/${path}`);Object.entries(params||{}).forEach(([k,v])=>u.searchParams.set(k,String(v)));const r=await fetch(u,{headers:{Accept:"application/json",Authorization:`apikey ${key}`}});const d=await r.json().catch(()=>({}));if(!r.ok||d.status==="error"||d.code)throw new Error(d.message||`Twelve Data ${r.status}`);return d;}
function tdSymbol(t){return t==="GOLD"?"XAU/USD":t==="SILVER"?"XAG/USD":t==="OIL"?"WTI/USD":t;}
function pct(a,b){return a!=null&&b?((a-b)/b)*100:null;}
function stochastic(series,period=14){const out=[];for(let i=0;i<series.length;i++){if(i<period-1){out.push({time:series[i].time,value:null});continue;}const w=series.slice(i-period+1,i+1),hi=Math.max(...w.map(x=>x.high)),lo=Math.min(...w.map(x=>x.low)),c=series[i].close;out.push({time:series[i].time,value:hi===lo?50:((c-lo)/(hi-lo))*100});}const value=out.length?out[out.length-1].value:null;const zone=value==null?"Unavailable":value>=80?"Overbought / extended":value<=20?"Oversold / stretched":"Neutral momentum zone";return {value:value==null?null:Number(value.toFixed(1)),zone,points:out.filter(x=>x.value!=null).map(x=>({time:x.time,value:Number(x.value.toFixed(1))})),note:"20/80 are momentum-extreme reference levels, not automatic buy/sell signals."};}
function dedupeNews(items){const seen=new Set();return (items||[]).filter(x=>{const h=String(x.headline||x.title||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim();const key=h.split(" ").slice(0,12).join(" ");if(!key||seen.has(key))return false;seen.add(key);return true;});}
async function companyNews(symbol,fh){if(!fh||!STOCKS.has(symbol)||symbol==="QQQ")return [];const now=new Date(),from=new Date(now.getTime()-7*864e5).toISOString().slice(0,10),to=now.toISOString().slice(0,10);try{const d=await finnhub(`company-news?symbol=${encodeURIComponent(symbol)}&from=${from}&to=${to}`,fh);return dedupeNews(Array.isArray(d)?d:[]).slice(0,12).map(x=>({headline:x.headline,summary:x.summary,source:x.source,url:x.url,datetime:x.datetime?new Date(x.datetime*1000).toISOString():null}));}catch{return [];}}
async function stockSnapshot(symbol,fh){const q=await finnhub(`quote?symbol=${encodeURIComponent(symbol)}`,fh);return {ticker:symbol,name:NAMES[symbol]||symbol,price:num(q.c),open:num(q.o),high:num(q.h),low:num(q.l),previousClose:num(q.pc),changeVsPreviousClosePct:num(q.dp)??pct(num(q.c),num(q.pc)),changeFromOpenPct:pct(num(q.c),num(q.o)),provider:"Finnhub"};}
async function tdSnapshot(symbol,td){const s=tdSymbol(symbol),q=await twelve("quote",{symbol:s,interval:"1day"},td);const price=num(q.close),prev=num(q.previous_close),open=num(q.open);return {ticker:symbol,name:q.name||NAMES[symbol]||symbol,price,open,high:num(q.high),low:num(q.low),previousClose:prev,changeVsPreviousClosePct:num(q.percent_change)??pct(price,prev),changeFromOpenPct:pct(price,open),provider:"Twelve Data",resolvedSymbol:s};}
async function history(symbol,fh,td){if(td){try{const d=await twelve("time_series",{symbol:tdSymbol(symbol),interval:"1day",outputsize:"40",order:"ASC"},td);const vals=Array.isArray(d.values)?d.values:[];if(vals.length)return vals.map(v=>({time:v.datetime,open:num(v.open),high:num(v.high),low:num(v.low),close:num(v.close),volume:num(v.volume)})).filter(x=>x.close!=null);}catch{}}
if(fh&&STOCKS.has(symbol)){try{const to=Math.floor(Date.now()/1000),from=to-60*86400,d=await finnhub(`stock/candle?symbol=${encodeURIComponent(symbol)}&resolution=D&from=${from}&to=${to}`,fh);if(d.s==="ok"&&Array.isArray(d.c))return d.c.map((c,i)=>({time:new Date(d.t[i]*1000).toISOString(),open:num(d.o[i]),high:num(d.h[i]),low:num(d.l[i]),close:num(c),volume:num(d.v?.[i])}));}catch{}}return [];}
function volumeVsAverage(series){const vols=series.map(x=>num(x.volume)).filter(x=>x!=null&&x>0);if(vols.length<2)return null;const cur=vols[vols.length-1],prev=vols.slice(Math.max(0,vols.length-21),-1);const avg=prev.reduce((a,b)=>a+b,0)/(prev.length||1);return avg?((cur-avg)/avg)*100:null;}
function driverText(driver,asset,osc){const key=String(driver||"macro").toLowerCase();const ch=num(asset.changeVsPreviousClosePct)||0,fromOpen=num(asset.changeFromOpenPct)||0,vol=num(asset.volumeVsAveragePct);let impact=Math.abs(ch)>=2?"High current price impact":"Moderate current price impact";const evidence=[`${asset.ticker} is ${ch>=0?"up":"down"} ${Math.abs(ch).toFixed(2)}% versus the previous close.`,fromOpen!=null?`From today's open the move is ${fromOpen>=0?"+":""}${fromOpen.toFixed(2)}%.`:null,vol!=null?`Latest volume is ${vol>=0?"above":"below"} its recent average by ${Math.abs(vol).toFixed(0)}%.`:null,osc.value!=null?`14-period Stochastic is ${osc.value.toFixed(1)} (${osc.zone}).`:null].filter(Boolean);let effect="MOVA is comparing this driver with current price action, momentum and participation.";let watch="Watch whether the driver and price continue moving in a consistent direction.";let confirm="Confirmation improves when price, volume and the wider market support the same conclusion.";let risk="Conflicting price action or fading volume reduces confidence.";
if(/yield|rate/.test(key)){effect="Treasury yields affect discount rates and can materially change growth-stock valuations; they also influence gold through real-yield opportunity cost.";watch="Watch the US 10-year yield and rate-expectation changes alongside the asset.";}
if(/volume/.test(key)){effect="Volume measures participation behind the price move; expanding volume can make a breakout or sell-off more credible.";watch="Compare current activity with the recent 20-session average.";}
if(/momentum|reversal|pressure/.test(key)){effect="Momentum shows whether buyers or sellers are sustaining directional pressure and whether the move is becoming stretched.";watch="Watch follow-through, failed breakouts, support/resistance and 20/80 momentum extremes.";}
if(/ai demand/.test(key)){effect="AI spending, hyperscaler capex and data-centre demand can move semiconductor and infrastructure earnings expectations.";watch="Watch guidance, customer capex, product demand and semiconductor peer confirmation.";}
return {impact,summary:`${NAMES[asset.ticker]||asset.ticker}: ${ch>=0?"positive":"negative"} session move with ${osc.zone.toLowerCase()} momentum. MOVA treats the selected driver as context unless the timing and market reaction provide stronger confirmation.`,evidence,effect,watch,confirm,risk};}
async function breadth(fh){const syms=["NVDA","MSFT","AAPL","AMZN","META","GOOGL","AVGO","TSLA"],rows=[];if(!fh)return null;for(const s of syms){try{const q=await finnhub(`quote?symbol=${s}`,fh);rows.push({symbol:s,changePct:num(q.dp)});}catch{}}return {label:"Large-cap technology breadth",advancing:rows.filter(x=>(x.changePct||0)>0).length,declining:rows.filter(x=>(x.changePct||0)<0).length,rows};}
async function scanOne(symbol,fh,td){let a;if(fh&&STOCKS.has(symbol))a=await stockSnapshot(symbol,fh);else if(td)a=await tdSnapshot(symbol,td);else throw new Error("No provider available");const s=await history(symbol,fh,td);const prevMove=s.length>=3?pct(s[s.length-2].close,s[s.length-3].close)||0:0;const move=num(a.changeVsPreviousClosePct)||0,vol=volumeVsAverage(s),osc=stochastic(s);let signal=Math.abs(move)<0.35?"watch":move>=2?"breakout":move<=-2?"move_down":move>0?"move_up":"reversal_down";let confidence=clamp(55+Math.min(20,Math.abs(move)*5)+(vol!=null?Math.min(10,Math.abs(vol)/10):0)+(osc.value!=null&&((move>0&&osc.value>50)||(move<0&&osc.value<50))?5:0));const tags=[move>=0?"Momentum ↑":"Pressure ↑",vol!=null&&vol>20?"Volume ↑":"Volume",symbol==="GOLD"?"Yields":symbol==="OIL"?"Supply":symbol==="NVDA"?"AI demand":"Rates"];return {ticker:symbol,name:a.name||NAMES[symbol]||symbol,move:Number(move.toFixed(2)),prevMove:Number(prevMove.toFixed(2)),signal,why:`Current move is ${Math.abs(move).toFixed(2)}% versus the previous close. ${vol==null?"Volume confirmation is unavailable.":`Volume is ${vol>=0?"above":"below"} its recent average.`} Momentum is ${osc.zone.toLowerCase()}.`,tags,confidence:Number(confidence.toFixed(0)),volumeVsAveragePct:vol,oscillator:osc.value,provider:a.provider};}
async function driverMode(u,fh,td){const ticker=alias(u.searchParams.get("ticker")||"NVDA"),driver=u.searchParams.get("driver")||"Momentum";let asset;if(fh&&STOCKS.has(ticker))asset=await stockSnapshot(ticker,fh);else if(td)asset=await tdSnapshot(ticker,td);else throw new Error("No provider available");asset.series=await history(ticker,fh,td);asset.volumeVsAveragePct=volumeVsAverage(asset.series);const oscillator=stochastic(asset.series),analysis=driverText(driver,asset,oscillator),headlines=await companyNews(ticker,fh);let proxy=null,breadthData=null,p=PROXIES[String(driver).toLowerCase()];if(p?.breadth)breadthData=await breadth(fh);return {asOf:new Date().toISOString(),method:"Live/near-live price, history, volume, momentum and current-news analysis",asset,oscillator,analysis,proxy,breadth:breadthData,headlines};}
export default{async fetch(request){if(request.method!=="GET")return Response.json({error:"Method not allowed"},{status:405});const fh=process.env.FINNHUB_API_KEY,td=process.env.TWELVE_DATA_API_KEY;if(!fh&&!td)return Response.json({error:"Set FINNHUB_API_KEY and/or TWELVE_DATA_API_KEY"},{status:500});const u=new URL(request.url);try{if(u.searchParams.get("mode")==="driver")return Response.json(await driverMode(u,fh,td),{headers:{"Cache-Control":"no-store"}});const symbols=(u.searchParams.get("symbols")||"NVDA,QQQ,GOLD,OIL,AAPL,MSFT").split(",").map(alias).filter(Boolean),items=[],errors=[];for(const s of symbols){try{items.push(await scanOne(s,fh,td));}catch(e){errors.push({ticker:s,error:e.message});}}return Response.json({asOf:new Date().toISOString(),items,errors},{headers:{"Cache-Control":"public, s-maxage=30, stale-while-revalidate=60"}});}catch(e){return Response.json({error:e.message||"Monitor failed"},{status:500});}}};
